# Generated by Django 4.2.11 on 2026-06-24 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_raw_text', models.TextField()),
                ('job_description', models.TextField(blank=True, default='')),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mercadopago', 'MercadoPago')], max_length=20)),
                ('payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('free_content', models.JSONField(default=dict)),
                ('paid_content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Análisis',
                'verbose_name_plural': 'Reportes de Análisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
