# Generated by Django 4.2.11 on 2026-06-24 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysis_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='paid_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
