# Generated by Django 4.2.11 on 2026-07-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_softskills_roleplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoriasession',
            name='rol_it_sesion',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Fullstack Developer'), ('devops', 'DevOps Engineer'), ('data_engineer', 'Data Engineer'), ('qa', 'QA/Tester'), ('architect', 'Solutions Architect'), ('scrum_master', 'Scrum Master'), ('product_manager', 'Product Manager'), ('tech_lead', 'Tech Lead'), ('ml_engineer', 'ML/AI Engineer'), ('security', 'Security Engineer'), ('cloud_engineer', 'Cloud Engineer')], help_text='Rol IT del usuario al iniciar esta sesión', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='rol_it_sesion',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Fullstack Developer'), ('devops', 'DevOps Engineer'), ('data_engineer', 'Data Engineer'), ('qa', 'QA/Tester'), ('architect', 'Solutions Architect'), ('scrum_master', 'Scrum Master'), ('product_manager', 'Product Manager'), ('tech_lead', 'Tech Lead'), ('ml_engineer', 'ML/AI Engineer'), ('security', 'Security Engineer'), ('cloud_engineer', 'Cloud Engineer')], help_text='Rol IT del usuario al iniciar esta sesión', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol_it_preferido',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Fullstack Developer'), ('devops', 'DevOps Engineer'), ('data_engineer', 'Data Engineer'), ('qa', 'QA/Tester'), ('architect', 'Solutions Architect'), ('scrum_master', 'Scrum Master'), ('product_manager', 'Product Manager'), ('tech_lead', 'Tech Lead'), ('ml_engineer', 'ML/AI Engineer'), ('security', 'Security Engineer'), ('cloud_engineer', 'Cloud Engineer')], help_text='Rol del usuario en IT para personalizar soft skills', max_length=20, null=True),
        ),
    ]
