# Generated by Django 4.2.11 on 2026-07-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mentoriasession_rol_it_sesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplaysession',
            name='regenerate_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='scenario_generated',
            field=models.JSONField(blank=True, help_text='Escenario generado dinámicamente basado en el rol IT', null=True),
        ),
        migrations.AlterField(
            model_name='roleplaysession',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.softskillsscenario'),
        ),
    ]
