# Generated by Django 4.2.11 on 2026-08-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mentoriasubscription_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoriasession',
            name='regenerate_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
